name: Code style check

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  check_linting:
    name: Check linting using the reusable workflow
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_lint.yml@v1
    with:
      source: './src'
      extensions: 'h,c'

  misspell:
    name: Check misspellings
    runs-on: ubuntu-latest
    steps:
    - name: Clone
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Check misspellings
      uses: codespell-project/actions-codespell@2391250ab05295bddd51e36a8c6295edb6343b0e
      with:
        builtin: clear,rare
        check_filenames: true
